{
 "title": "Micrometer Spring Throughput - Mimir",
 "description": "Micrometer Http throughput dashboard ",
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   { "name": "datasource", "label": "Datasource", "query": "prometheus" },
   { "name": "application", "label": "Application", "query": { "query": "label_values(application)" } },
   {
    "name": "host",
    "label": "host",
    "query": {
     "query": "label_values(process_uptime{application=\"$application\"}, instance)"
    }
   },
   { "name": "log_search", "label": "Log Search" }
  ]
 },
 "panels": [
  { "title": "Logs", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Logs",
   "type": "logs",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 1 },
   "targets": [
    {
     "expr": "{application=\"$application\", host=\"$host\"} |= `${log_search}`"
    }
   ]
  },
  {
   "title": "Status and SLA",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 7 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Status",
   "type": "stat",
   "gridPos": { "h": 4, "w": 2, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "clamp_max(process_uptime{application=\"${application}\", instance=\"${host}\"}, 1)"
    }
   ]
  },
  {
   "title": "Response time",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 22, "x": 2, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(http_server_requests{application=\"$application\", instance=\"$host\"}) by (quantile)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Up Time",
   "type": "stat",
   "gridPos": { "h": 4, "w": 2, "x": 0, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "process_uptime{application=\"$application\", instance=\"$host\"}"
    }
   ]
  },
  {
   "title": "Throughput",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 16 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Requests per second",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "rate(http_server_requests_count{application=\"$application\", instance=\"$host\"}[1m])",
     "legendFormat": "{{method}}-{{status}}-{{uri}}"
    }
   ]
  },
  {
   "title": "Mean response time",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 8, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "rate(http_server_requests_sum{application=\"$application\", instance=\"$host\"}[1m])/rate(http_server_requests_count{application=\"$application\", instance=\"$host\"}[1m])",
     "legendFormat": "{{method}}-{{status}}-{{uri}}"
    }
   ]
  },
  {
   "title": "Top 10 APIs",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 16, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "topk(10, sum by(uri, method) (rate(http_server_requests_count{application=\"$application\", instance=\"$host\"}[1m])))"
    }
   ]
  }
 ]
}