{
 "title": "Agent Monitoring",
 "description": "[15983] Visualize OpenTelemetry (OTEL) collector metrics (tested with AWS OTEL/ADOT v0.21.0 / OTEL v0.72.0)",
 "tags": [
  "agent",
  "opentelemetry"
 ],
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   { "name": "datasource", "label": "Datasource", "query": "prometheus" },
   { "name": "minstep", "label": "Min step", "query": "10s,30s,1m,5m" },
   { "name": "receiver", "label": "Receiver", "query": { "query": "label_values(receiver)" } },
   { "name": "processor", "label": "Processor", "query": { "query": "label_values(processor)" } },
   { "name": "exporter", "label": "Exporter", "query": { "query": "label_values(exporter)" } }
  ]
 },
 "panels": [
  { "title": "Logs", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Dropped logs ($__interval)",
   "type": "stat",
   "gridPos": { "h": 7, "w": 5, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate({application=\"otelcontribcol-agent\", action=\"drop\"} | json | level = `error` [$__interval]))",
     "legendFormat": "{{metadata_dropped_component_id}}"
    }
   ]
  },
  {
   "title": "Dropped logs",
   "type": "logs",
   "gridPos": { "h": 7, "w": 19, "x": 5, "y": 1 },
   "targets": [
    {
     "expr": "{application=\"otelcontribcol-agent\", level=\"error\", action=\"drop\"} |= ``"
    }
   ]
  },
  {
   "title": "Agent errors ($__interval)",
   "type": "stat",
   "gridPos": { "h": 7, "w": 5, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate({application=\"otelcontribcol-agent\"} | json | level = `error` [$__interval]))",
     "legendFormat": "{{metadata_dropped_component_id}}"
    }
   ]
  },
  {
   "title": "Agent Logs (ERROR)",
   "type": "logs",
   "gridPos": { "h": 7, "w": 19, "x": 5, "y": 8 },
   "targets": [
    {
     "expr": "{application=\"otelcontribcol-agent\", level=\"error\"} |= ``"
    }
   ]
  },
  {
   "title": "Receivers",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 15 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Spans Rate",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(rate(otelcol_receiver_accepted_spans{receiver=~\"$receiver\"}[$__rate_interval])) by (receiver)",
     "legendFormat": "Accepted rate: {{receiver}}"
    },
    {
     "expr": "sum(rate(otelcol_receiver_refused_spans{receiver=~\"$receiver\"}[$__rate_interval])) by (receiver)",
     "legendFormat": "Refused rate: {{receiver}}"
    }
   ]
  },
  {
   "title": "Metric Points Rate",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(rate(otelcol_receiver_accepted_metric_points{receiver=~\"$receiver\"}[$__rate_interval])) by (receiver)",
     "legendFormat": "Accepted rate: {{receiver}}"
    },
    {
     "expr": "sum(rate(otelcol_receiver_refused_metric_points{receiver=~\"$receiver\"}[$__rate_interval])) by (receiver)",
     "legendFormat": "Refused rate: {{receiver}}"
    }
   ]
  },
  {
   "title": "Processors",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 25 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Spans Rate",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(rate(otelcol_processor_accepted_spans{processor=~\"$processor\"}[$__rate_interval])) by (processor)",
     "legendFormat": "Accepted rate: {{processor}}"
    },
    {
     "expr": "sum(rate(otelcol_processor_refused_spans{processor=~\"$processor\"}[$__rate_interval])) by (processor)",
     "legendFormat": "Refused rate: {{processor}}"
    },
    {
     "expr": "sum(rate(otelcol_processor_dropped_spans{processor=~\"$processor\"}[$__interval])) by (processor)",
     "legendFormat": "Dropped rate: {{processor}}"
    }
   ]
  },
  {
   "title": "Batch Metrics",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(rate(otelcol_processor_batch_batch_send_size_count{processor=~\"$processor\"}[$__rate_interval])) by (processor)",
     "legendFormat": "Batch send size count: {{processor}}"
    },
    {
     "expr": "sum(rate(otelcol_processor_batch_batch_send_size_sum{processor=~\"$processor\"}[$__rate_interval])) by (processor)",
     "legendFormat": "Batch send size sum: {{processor}}"
    }
   ]
  },
  {
   "title": "Exporters",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 35 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Spans Rate",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 36 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(rate(otelcol_exporter_sent_spans{exporter=~\"$exporter\"}[$__rate_interval])) by (exporter)",
     "legendFormat": "Sent spans rate: {{exporter}}"
    },
    {
     "expr": "sum(rate(otelcol_exporter_enqueue_failed_spans{exporter=~\"$exporter\"}[$__rate_interval])) by (exporter)",
     "legendFormat": "Enqueue failed spans rate: {{exporter}}"
    }
   ]
  },
  {
   "title": "Metric Points Rate",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 36 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(rate(otelcol_exporter_sent_metric_points{exporter=~\"$exporter\"}[$__rate_interval])) by (exporter)",
     "legendFormat": "Sent metric points: {{exporter}}"
    },
    {
     "expr": "sum(rate(otelcol_exporter_enqueue_failed_metric_points{exporter=~\"$exporter\"}[$__rate_interval])) by (exporter)",
     "legendFormat": "Enqueue failed metric points rate: {{exporter}}"
    }
   ]
  },
  {
   "title": "Exporter Queue Size",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 45 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "max(otelcol_exporter_queue_size{exporter=~\"$exporter\"}) by (exporter)",
     "legendFormat": "Max queue size: {{exporter}}"
    }
   ]
  },
  {
   "title": "Failed Request Rate",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 45 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(rate(otelcol_exporter_send_failed_requests{}[$__rate_interval]))",
     "legendFormat": "Failed request rate: {{exporter}}"
    }
   ]
  },
  {
   "title": "Collector",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 54 },
   "targets": [
    {}
   ]
  },
  {
   "title": "CPU Usage",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 55 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "max(rate(otelcol_process_cpu_seconds{}[$__rate_interval])*100) by (instance)",
     "legendFormat": "Max CPU usage"
    },
    {
     "expr": "avg(rate(otelcol_process_cpu_seconds{}[$__rate_interval])*100) by (instance)",
     "legendFormat": "Avg CPU usage"
    },
    {
     "expr": "min(rate(otelcol_process_cpu_seconds{}[$__rate_interval])*100) by (instance)",
     "legendFormat": "Min CPU usage"
    }
   ]
  },
  {
   "title": "Memory RSS",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 55 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "max(otelcol_process_memory_rss{})",
     "legendFormat": "Max Memory RSS"
    },
    {
     "expr": "avg(otelcol_process_memory_rss{})",
     "legendFormat": "Avg Memory RSS"
    },
    {
     "expr": "min(otelcol_process_memory_rss{})",
     "legendFormat": "Min Memory RSS"
    }
   ]
  },
  {
   "title": "Service Instance Count",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 64 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "count(count(otelcol_process_cpu_seconds{service_instance_id=~\".*\"}) by (service_instance_id))",
     "legendFormat": "Service instance count"
    }
   ]
  },
  {
   "title": "Documentation",
   "type": "text",
   "gridPos": { "h": 3, "w": 24, "x": 0, "y": 73 },
   "options": {
    "content": "<a href=\"http://www.monitoringartist.com\" target=\"_blank\" title=\"Dashboard maintained by Monitoring Artist - DevOps / Docker / Kubernetes / AWS ECS / Google GCP / Zabbix / Zenoss / Terraform / Monitoring\"><img src=\"https://monitoringartist.github.io/monitoring-artist-logo-grafana.png\" height=\"30px\" /></a> | \n<a target=\"_blank\" href=\"https://github.com/open-telemetry/opentelemetry-collector/blob/main/docs/troubleshooting.md#metrics\">OTEL collector troubleshooting (how to enable telemetry metrics)</a> | \n<a target=\"_blank\" href=\"https://grafana.com/grafana/dashboards/15983\">Installed from Grafana.com dashboards</a>"
   },
   "targets": [
    {}
   ]
  }
 ]
}