receivers:
  filelog:
    include: [ /app/log/*.log ]
    storage: file_storage/client
    operators:
      - type: key_value_parser
        delimiter: "="
        pair_delimiter: "\t"
        timestamp:
          parse_from: attributes.timestamp
          layout_type: gotime
          layout: '2006/01/02 15:04:05.999'

exporters:
  file/no_rotation:
    path: /app/otelcontribcol.debug

extensions:
  health_check:
  pprof:
  zpages:
  file_storage/client:
    directory: /app/logstate/client

service:
  extensions: [file_storage/client, health_check, pprof, zpages]
  pipelines:
    logs:
      receivers: [filelog]
      exporters: [file/no_rotation]