receivers:
  filelog:
    include: [ /app/log/*.log ]
    storage: file_storage/client
    attributes:
      service.name: client
      application: ${service.name}
      host: ${env:HOSTNAME}
    operators:
      - type: key_value_parser
        delimiter: "="
        pair_delimiter: "\t"
        timestamp:
          parse_from: attributes.timestamp
          layout_type: gotime
          layout: '2006/01/02 15:04:05.999'

exporters:
  file/no_rotation:
    path: /app/otelcontribcol.debug
  loki:
    endpoint: http://loki:3100/loki/api/v1/push

processors:
  attributes/loki:
    actions:
      - action: insert
        key: loki.attribute.labels
        value: H, host, application, service.name

extensions:
  health_check:
  pprof:
  zpages:
  file_storage/client:
    directory: /app/logstate/client

service:
  extensions: [file_storage/client, health_check, pprof, zpages]
  pipelines:
    logs:
      receivers: [filelog]
      processors: [attributes/loki]
      exporters: [file/no_rotation, loki]