# keep version only for graphviz
version: '3.8'
services:
  consul-server:
    image: hashicorp/consul:${CONSUL_VERSION}
    restart: always
    volumes:
      - ./consul.d/server/server.json:/consul/config/server.json:ro
    networks:
      - bridge
    ports:
      - 8500:8500
    command: "agent"

  service:
    build:
      context: ./service
      args:
        - CONSUL_VERSION=${CONSUL_VERSION}
        - JDK_IMAGE=${JDK_IMAGE}
        - DISTRO=${DISTRO}
        - OTEL_JAVA_AGENT_VERSION=${OTEL_JAVA_AGENT_VERSION}
        - VECTOR_VERSION=${VECTOR_VERSION}
    deploy:
      replicas: 4
    networks:
      - bridge
    volumes:
      - ./agents/vector/agent/:/app/vector_config/:ro
    environment:
      # TODO set -log-level info instead of error when consul agent will be fixed https://developer.hashicorp.com/consul/docs/upgrading/upgrade-specific#deprecating-authentication-via-token-query-parameter
      - CONSUL_ARGS=-log-level error -log-json -retry-join consul-server
      - SERVICE_NAME=users-service
      - SERVICE_ENV=dev
      - OTEL_EXPORTER_OTLP_PROTOCOL=grpc
      - OTEL_EXPORTER_OTLP_ENDPOINT=http://tempo:4317
      - OTEL_METRICS_EXPORTER=none
    depends_on:
      - consul-server
      - mimir
      - loki
      - tempo

  client:
    build:
      context: ./client
      args:
        - CONSUL_VERSION=${CONSUL_VERSION}
        - JDK_IMAGE=${JDK_IMAGE}
        - DISTRO=${DISTRO}
        - OTEL_JAVA_AGENT_VERSION=${OTEL_JAVA_AGENT_VERSION}
        - OTEL_CONTRIB_COL=${OTEL_CONTRIB_COL}
    networks:
      - bridge
    volumes:
      - ./agents/otelcontribcol/agent/:/etc/otelcol-contrib/:ro
    environment:
      # TODO set -log-level info instead of error when consul agent will be fixed https://developer.hashicorp.com/consul/docs/upgrading/upgrade-specific#deprecating-authentication-via-token-query-parameter
      - CONSUL_ARGS=-log-level error -log-json -retry-join consul-server
      - SERVICE_NAME=client
      - SERVICE_ENV=dev
      - OTEL_EXPORTER_OTLP_PROTOCOL=grpc
      - OTEL_EXPORTER_OTLP_ENDPOINT=http://tempo:4317
      - OTEL_METRICS_EXPORTER=none
    ports:
      - 8080:8080
    depends_on:
      - consul-server
      - mimir
      - loki
      - tempo
      - service

  curl:
    image: curlimages/curl:8.3.0
    networks:
      - bridge
    entrypoint: sh -c "watch -n 0.5 -d -- curl http://client:8080/hello 2>&1 > /dev/null"
    depends_on:
      - client

  prometheus:
    build:
      context: ./prometheus
      args:
        - CONSUL_VERSION=${CONSUL_VERSION}
        - PROMETHEUS_VERSION=${PROMETHEUS_VERSION}
    networks:
      - bridge
    environment:
      - CONSUL_ARGS=-retry-join consul-server
      - SERVICE_NAME=prometheus
    volumes:
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml:ro
    ports:
      - 9090:9090
    depends_on:
      - consul-server

  loki:
    image: grafana/loki:2.9.1
    command: -config.file=/etc/loki/local-config.yaml -validation.reject-old-samples=false -query-scheduler.max-outstanding-requests-per-tenant=2048 -querier.max-outstanding-requests-per-tenant=2048
    volumes:
      - ./loki/:/etc/loki/:ro
    networks:
      - bridge

  mimir:
    image: grafana/mimir:2.10.0
    volumes:
      - ./mimir/mimir.yaml:/etc/mimir.yaml
    command: --config.file=/etc/mimir.yaml
    networks:
      - bridge

  tempo:
    image: grafana/tempo:2.2.3
    volumes:
      - ./tempo/tempo-local.yaml:/etc/tempo.yaml:ro
    command: [ "-config.file=/etc/tempo.yaml" ]
    networks:
      - bridge

  graphite:
    image: graphiteapp/graphite-statsd:1.1.10-4
    networks:
      - bridge

  grafana:
    image: grafana/grafana-oss:10.1.2
    environment:
      - GF_AUTH_ANONYMOUS_ENABLED=true
      - GF_AUTH_ANONYMOUS_ORG_ROLE=Admin
    ports:
      - 3000:3000
    networks:
      - bridge
    volumes:
      - ./grafana/grafana.ini:/etc/grafana/grafana.ini:ro
      - ./grafana/provisioning/:/etc/grafana/provisioning/:ro
    depends_on:
      - mimir
      - prometheus
      - loki
      - tempo

networks:
  bridge: