# keep version only for graphviz
version: '3.8'
services:
  consul-server:
    image: hashicorp/consul:1.15.2
    restart: always
    volumes:
     - ./consul.d/server/server.json:/consul/config/server.json:ro
    networks:
      - bridge
    ports:
      - 8500:8500
    command: "agent"

  service:
    build: 
      context: ./service
    deploy:
      replicas: 4
    networks:
      - bridge
    environment:
      - CONSUL_ARGS=-retry-join consul-server
      - SERVICE_NAME=users-service
      - SERVICE_ENV=dev
      - OTEL_EXPORTER_OTLP_PROTOCOL=grpc
      - OTEL_EXPORTER_OTLP_ENDPOINT=http://tempo:4317
      - OTEL_METRICS_EXPORTER=none
    depends_on:
      - consul-server
      - loki
      - tempo

  client:
    build: 
      context: ./client
    networks:
      - bridge
    environment:
      - CONSUL_ARGS=-retry-join consul-server
      - SERVICE_NAME=client
      - SERVICE_ENV=dev
      - OTEL_EXPORTER_OTLP_PROTOCOL=grpc
      - OTEL_EXPORTER_OTLP_ENDPOINT=http://tempo:4317
      - OTEL_METRICS_EXPORTER=none
    ports:
      - 8080:8080
    depends_on:
      - consul-server
      - loki
      - tempo
      - service

  curl:
    image: alpine/curl
    networks:
      - bridge
    entrypoint: sh -c "watch -n 0.5 -d -- curl http://client:8080/hello 2>&1 > /dev/null"
    depends_on:
      - client

  prometheus:
    build: 
      context: ./prometheus
    networks:
      - bridge
    environment:
      - CONSUL_ARGS=-retry-join consul-server
      - SERVICE_NAME=prometheus
    volumes:
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml:ro
    ports:
      - 9090:9090
    depends_on:
      - consul-server

  loki:
    image: grafana/loki:2.7.5
    command: -config.file=/etc/loki/local-config.yaml -query-scheduler.max-outstanding-requests-per-tenant=2048 -querier.max-outstanding-requests-per-tenant=2048
    volumes:
      - ./loki/:/etc/loki/:ro
    networks:
      - bridge

  mimir:
    image: grafana/mimir:2.7.1
    volumes:
      - ./mimir/mimir.yaml:/etc/mimir.yaml
    command: --config.file=/etc/mimir.yaml
    networks:
      - bridge

  tempo:
    image: grafana/tempo:2.0.1
    volumes:
      - ./tempo/tempo-local.yaml:/etc/tempo.yaml:ro
    command: [ "-config.file=/etc/tempo.yaml" ]
    networks:
      - bridge

  grafana:
    image: grafana/grafana-oss:9.4.7
    environment:
      - GF_AUTH_ANONYMOUS_ENABLED=true
      - GF_AUTH_ANONYMOUS_ORG_ROLE=Admin
    ports:
      - 3000:3000
    networks:
      - bridge
    volumes:
      - ./grafana/grafana.ini:/etc/grafana/grafana.ini:ro
      - ./grafana/provisioning/:/etc/grafana/provisioning/:ro
    depends_on:
      - prometheus
      - loki
      - tempo

networks:
  bridge: