logging:
  level: 
    root: INFO
    com.service.app.consul.session: DEBUG
    org.springframework.jdbc.core: TRACE

spring:
  cloud:
    consul:
      host: localhost
      discovery:
        instance-id: ${spring.application.name}-${server.port}
        query-passing: true
        prefer-ip-address: true
        tags: batch

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,prometheus 
    jmx:
      exposure:
        include: '*'