apiVersion: 1

datasources:
- name: Mimir
  type: prometheus
  uid: mimir
  access: proxy
  orgId: 1
  url: http://mimir:9009/prometheus
  basicAuth: false
  isDefault: true
  editable: false