{
 "title": "JVM (Micrometer All instances)",
 "description": "Dashboard for Micrometer instrumented applications (Java, Spring Boot, Micronaut)",
 "time": { "from": "now-30m", "to": "now" },
 "templating": {
  "list": [
   { "name": "datasource", "query": "prometheus" },
   { "name": "job", "label": "Application", "query": { "query": "label_values(application)" } },
   { "name": "env", "label": "Environment", "query": { "query": "label_values(env)" } },
   {
    "name": "jvm_memory_pool_heap",
    "label": "JVM Memory Pools Heap",
    "query": {
     "query": "label_values(jvm_memory_used_bytes{application=\"$job\", area=\"heap\"},id)"
    }
   },
   {
    "name": "jvm_memory_pool_nonheap",
    "label": "JVM Memory Pools Non-Heap",
    "query": {
     "query": "label_values(jvm_memory_used_bytes{application=\"$job\", area=\"nonheap\"},id)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Quick Facts",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Uptime",
   "type": "stat",
   "gridPos": { "h": 3, "w": 6, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "min(process_uptime_seconds{application=\"$job\", env=\"$env\"})",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Heap used",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 9, "x": 6, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "sum by (instance) (jvm_memory_used_bytes{application=\"$job\", area=\"heap\", env=\"$env\"})*100/sum by (instance) (jvm_memory_max_bytes{application=\"$job\", area=\"heap\", env=\"$env\"})",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Non-Heap used",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 9, "x": 15, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "sum by (instance) (jvm_memory_used_bytes{application=\"$job\", env=\"$env\", area=\"nonheap\"})*100/sum by(instance) (jvm_memory_max_bytes{application=\"$job\", env=\"$env\", area=\"nonheap\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Start time",
   "type": "stat",
   "gridPos": { "h": 3, "w": 6, "x": 0, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "dateTimeAsIso" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "min(process_start_time_seconds{application=\"$job\", env=\"$env\"})*1000"
    }
   ]
  },
  {
   "title": "I/O Overview",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 7 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Rate",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    {
     "expr": "sum by(instance) (rate(http_server_requests_seconds_count{application=\"$job\", env=\"$env\"}[1m]))",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Errors 5xx",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    {
     "expr": "sum by (instance) (rate(http_server_requests_seconds_count{application=\"$job\", env=\"$env\", status=~\"5..\"}[1m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Duration (avg)",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "sum by (instance) (rate(http_server_requests_seconds_sum{application=\"$job\", env=\"$env\", status!~\"5..\"}[1m]))/sum by (instance) (rate(http_server_requests_seconds_count{application=\"$job\", env=\"$env\", status!~\"5..\"}[1m]))",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Utilisation",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "tomcat_threads_busy_threads{application=\"$job\", env=\"$env\"}",
     "legendFormat": "{{instance}}.tomcat.busy"
    },
    {
     "expr": "tomcat_threads_current{job=\"$job\", env=\"$env\"}",
     "legendFormat": "{{instance}}.tomcat.current"
    },
    {
     "expr": "tomcat_threads_config_max{job=\"$job\", env=\"$env\", instance=\"$instance\"}",
     "legendFormat": "{{instance}}.tomcat.max"
    },
    {
     "expr": "jetty_threads_busy{job=\"$job\", env=\"$env\", instance=\"$instance\"}",
     "legendFormat": "{{instance}}.jetty.busy"
    },
    {
     "expr": "jetty_threads_current{job=\"$job\", env=\"$env\", instance=\"$instance\"}",
     "legendFormat": "{{instance}}.jetty.current"
    },
    {
     "expr": "jetty_threads_config_max{job=\"$job\", env=\"$env\", instance=\"$instance\"}",
     "legendFormat": "{{instance}}.jetty.max"
    }
   ]
  },
  {
   "title": "JVM Memory",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 20 },
   "targets": [
    {}
   ]
  },
  {
   "title": "JVM Total",
   "type": "timeseries",
   "gridPos": { "h": 14, "w": 12, "x": 0, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum by (instance) (jvm_memory_used_bytes{application=\"$job\", env=\"$env\"})",
     "legendFormat": "{{instance}}.used"
    },
    {
     "expr": "sum by (instance) (jvm_memory_committed{job=\"$job\", env=\"$env\"})",
     "legendFormat": "{{instance}}.committed"
    },
    {
     "expr": "sum by (instance) (jvm_memory_max{job=\"$job\", env=\"$env\"})",
     "legendFormat": "{{instance}}.max"
    }
   ]
  },
  {
   "title": "JVM Non-Heap",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum by (instance) (jvm_memory_used_bytes{application=\"$job\", env=\"$env\", area=\"nonheap\"})",
     "legendFormat": "{{instance}}.used"
    },
    {
     "expr": "sum(jvm_memory_committed{job=\"$job\", env=\"$env\", instance=\"$instance\", area=\"nonheap\"})",
     "legendFormat": "{{instance}}.committed"
    },
    {
     "expr": "sum(jvm_memory_max{job=\"$job\", env=\"$env\", instance=\"$instance\", area=\"nonheap\"})",
     "legendFormat": "{{instance}}.max"
    }
   ]
  },
  {
   "title": "JVM Heap",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 28 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum by (instance) (jvm_memory_used_bytes{application=\"$job\", env=\"$env\", area=\"heap\"})",
     "legendFormat": "{{instance}}.used"
    },
    {
     "expr": "sum by (instance) (jvm_memory_committed{job=\"$job\", env=\"$env\", area=\"heap\"})",
     "legendFormat": "{{instance}}.committed"
    },
    {
     "expr": "sum(jvm_memory_max{job=\"$job\", env=\"$env\", instance=\"$instance\", area=\"heap\"})",
     "legendFormat": "{{instance}}.max"
    }
   ]
  },
  {
   "title": "JVM Misc",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 35 },
   "targets": [
    {}
   ]
  },
  {
   "title": "CPU Usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 36 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "system_cpu_usage{application=\"$job\", env=\"$env\"}",
     "legendFormat": "{{instance}}.system"
    },
    {
     "expr": "process_cpu_usage{job=\"$job\", env=\"$env\"}",
     "legendFormat": "{{instance}}.process"
    },
    {
     "expr": "avg_over_time(process_cpu_usage{job=\"$job\", env=\"$env\"}[1h])",
     "legendFormat": "{{instance}}.process-1h"
    }
   ]
  },
  {
   "title": "Load",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 36 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "system_load_average_1m{application=\"$job\", env=\"$env\"}",
     "legendFormat": "{{instance}}.system-1m"
    },
    {
     "expr": "system_cpu_count{job=\"$job\", env=\"$env\"}",
     "legendFormat": "{{instance}}.cpus"
    }
   ]
  },
  {
   "title": "Threads",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 44 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "jvm_threads_live_threads{application=\"$job\", env=\"$env\"}",
     "legendFormat": "{{instance}}.live"
    },
    {
     "expr": "jvm_threads_daemon_threads{application=\"$job\", env=\"$env\"}",
     "legendFormat": "{{instance}}.daemon"
    },
    {
     "expr": "jvm_threads_peak_threads{application=\"$job\", env=\"$env\"}",
     "legendFormat": "{{instance}}.peak"
    },
    {
     "expr": "process_threads_threads{application=\"$job\", env=\"$env\"}",
     "legendFormat": "{{instance}}.process"
    }
   ]
  },
  {
   "title": "Thread States",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 44 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "jvm_threads_states_threads{application=\"$job\", env=\"$env\"}",
     "legendFormat": "{{instance}}..{{state}}"
    }
   ]
  },
  {
   "title": "Log Events",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 51 },
   "fieldConfig": { "defaults": { "unit": "opm" } },
   "targets": [
    {
     "expr": "increase(logback_events_total{application=\"$job\", env=\"$env\"}[1m])",
     "legendFormat": "{{instance}}.{{level}}"
    }
   ]
  },
  {
   "title": "File Descriptors",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 51 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "process_files_open_files{application=\"$job\", env=\"$env\"}",
     "legendFormat": "{{instance}}.open"
    },
    {
     "expr": "process_files_max_files{application=\"$job\", env=\"$env\"}",
     "legendFormat": "{{instance}}.max"
    }
   ]
  },
  {
   "title": "JVM Memory Pools (Heap)",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 58 },
   "repeat": "persistence_counts",
   "targets": [
    {}
   ]
  },
  {
   "title": "$jvm_memory_pool_heap",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 59 },
   "repeat": "jvm_memory_pool_heap",
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "jvm_memory_used_bytes{application=\"$job\", env=\"$env\", id=~\"$jvm_memory_pool_heap\"}",
     "legendFormat": "{{instance}}.used"
    },
    {
     "expr": "jvm_memory_committed_bytes{application=\"$job\", env=\"$env\", id=~\"$jvm_memory_pool_heap\"}",
     "legendFormat": "{{instance}}.commited"
    },
    {
     "expr": "jvm_memory_max_bytes{application=\"$job\", env=\"$env\", id=~\"$jvm_memory_pool_heap\"}",
     "legendFormat": "{{instance}}.max"
    }
   ]
  },
  {
   "title": "JVM Memory Pools (Non-Heap)",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 66 },
   "targets": [
    {}
   ]
  },
  {
   "title": "$jvm_memory_pool_nonheap",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 67 },
   "repeat": "jvm_memory_pool_nonheap",
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "jvm_memory_used_bytes{application=\"$job\", env=\"$env\", id=~\"$jvm_memory_pool_nonheap\"}",
     "legendFormat": "{{instance}}.used"
    },
    {
     "expr": "jvm_memory_committed_bytes{application=\"$job\", env=\"$env\", id=~\"$jvm_memory_pool_nonheap\"}",
     "legendFormat": "{{instance}}.commited"
    },
    {
     "expr": "jvm_memory_max_bytes{application=\"$job\", env=\"$env\", id=~\"$jvm_memory_pool_nonheap\"}",
     "legendFormat": "{{instance}}.max"
    }
   ]
  },
  {
   "title": "Garbage Collection",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 81 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Collections",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 82 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    {
     "expr": "rate(jvm_gc_pause_seconds_count{application=\"$job\", env=\"$env\"}[1m])",
     "legendFormat": "{{instance}}.{{action}} ({{cause}})"
    }
   ]
  },
  {
   "title": "Pause Durations",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 82 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "rate(jvm_gc_pause_seconds_sum{application=\"$job\", env=\"$env\"}[1m])/rate(jvm_gc_pause_seconds_count{application=\"$job\", env=\"$env\"}[1m])",
     "legendFormat": "{{instance}}.avg {{action}} ({{cause}})"
    },
    {
     "expr": "jvm_gc_pause_seconds_max{application=\"$job\", env=\"$env\"}",
     "legendFormat": "{{instance}}.max {{action}} ({{cause}})"
    }
   ]
  },
  {
   "title": "Allocated/Promoted",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 82 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "rate(jvm_gc_memory_allocated_bytes_total{application=\"$job\", env=\"$env\"}[1m])",
     "legendFormat": "{{instance}}.allocated"
    },
    {
     "expr": "rate(jvm_gc_memory_promoted_bytes_total{application=\"$job\", env=\"$env\"}[1m])",
     "legendFormat": "{{instance}}.promoted"
    }
   ]
  },
  {
   "title": "Classloading",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 89 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Classes loaded",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 90 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "jvm_classes_loaded_classes{application=\"$job\", env=\"$env\"}",
     "legendFormat": "{{instance}}.loaded"
    }
   ]
  },
  {
   "title": "Class delta",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 90 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "delta(jvm_classes_loaded_classes{application=\"$job\", env=\"$env\"}[1m])",
     "legendFormat": "{{instance}}.delta-1m"
    }
   ]
  },
  {
   "title": "Buffer Pools",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 97 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Direct Buffers",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 98 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "jvm_buffer_memory_used_bytes{application=\"$job\", env=\"$env\", id=\"direct\"}",
     "legendFormat": "{{instance}}.used"
    },
    {
     "expr": "jvm_buffer_total_capacity_bytes{application=\"$job\", env=\"$env\", id=\"direct\"}",
     "legendFormat": "{{instance}}.capacity"
    }
   ]
  },
  {
   "title": "Direct Buffers",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 6, "y": 98 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "jvm_buffer_count_buffers{application=\"$job\", env=\"$env\", id=\"direct\"}",
     "legendFormat": "{{instance}}.count"
    }
   ]
  },
  {
   "title": "Mapped Buffers",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 12, "y": 98 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "jvm_buffer_memory_used_bytes{application=\"$job\", env=\"$env\", id=\"mapped\"}",
     "legendFormat": "{{instance}}.used"
    },
    {
     "expr": "jvm_buffer_total_capacity_bytes{application=\"$job\", env=\"$env\", id=\"mapped\"}",
     "legendFormat": "{{instance}}.capacity"
    }
   ]
  },
  {
   "title": "Mapped Buffers",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 18, "y": 98 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "jvm_buffer_count_buffers{application=\"$job\", env=\"$env\", id=\"mapped\"}",
     "legendFormat": "{{instance}}.count"
    }
   ]
  }
 ]
}