{
 "title": "Micrometer Spring Throughput",
 "description": "Micrometer Http throughput dashboard ",
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   { "name": "datasource", "label": "Datasource", "query": "prometheus" },
   { "name": "application", "label": "Application", "query": { "query": "label_values(application)" } },
   {
    "name": "host",
    "label": "host",
    "query": {
     "query": "label_values(up{application=\"$application\"}, host)"
    }
   },
   { "name": "log_search", "label": "Log Search" }
  ]
 },
 "panels": [
  { "title": "Logs", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Logs",
   "type": "logs",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 1 },
   "targets": [
    {
     "expr": "{application=\"$application\", host=\"$host\"} |= `${log_search}`"
    }
   ]
  },
  {
   "title": "Status and SLA",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 7 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Status",
   "type": "stat",
   "gridPos": { "h": 4, "w": 2, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "up{application=\"${application}\", host=\"${host}\"}"
    }
   ]
  },
  {
   "title": "Number Requests that missed 50ms SLA",
   "type": "table-old",
   "gridPos": { "h": 8, "w": 22, "x": 2, "y": 8 },
   "targets": [
    {
     "expr": "http_server_requests_seconds_bucket{application=\"$application\", host=\"$host\", le=\"0.05\"}"
    }
   ]
  },
  {
   "title": "Up Time",
   "type": "stat",
   "gridPos": { "h": 4, "w": 2, "x": 0, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "process_uptime_seconds{application=\"$application\", host=\"$host\"}"
    }
   ]
  },
  {
   "title": "Throughput",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 16 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Requests per second",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "rate(http_server_requests_seconds_count{application=\"$application\", host=\"$host\"}[1m])",
     "legendFormat": "{{method}}-{{status}}-{{uri}}"
    }
   ]
  },
  {
   "title": "Mean response time",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "rate(http_server_requests_seconds_sum{application=\"$application\", host=\"$host\"}[1m])/rate(http_server_requests_seconds_count{application=\"$application\", host=\"$host\"}[1m])",
     "legendFormat": "{{method}}-{{status}}-{{uri}}"
    }
   ]
  },
  {
   "title": "Response time of 50%, 75%, 90%, 95% of requests",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum(rate(http_server_requests_seconds_bucket{application=\"$application\", host=\"$host\"}[1m])) by (le))",
     "legendFormat": "95%"
    },
    {
     "expr": "histogram_quantile(0.9, sum(rate(http_server_requests_seconds_bucket{application=\"$application\", host=\"$host\"}[1m])) by (le))",
     "legendFormat": "90%"
    },
    {
     "expr": "histogram_quantile(0.75, sum(rate(http_server_requests_seconds_bucket{application=\"$application\", host=\"$host\"}[1m])) by (le))",
     "legendFormat": "75%"
    },
    {
     "expr": "histogram_quantile(0.5, sum(rate(http_server_requests_seconds_bucket{application=\"$application\", host=\"$host\"}[1m])) by (le))",
     "legendFormat": "50%"
    }
   ]
  },
  {
   "title": "Top 10 APIs",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "topk(10, sum by(uri, method) (rate(http_server_requests_seconds_count{application=\"$application\"}[1m])))"
    }
   ]
  }
 ]
}