# https://vector.dev/docs/reference/configuration/transforms/remap/#examples-parse-key/value-logfmt-logs
# https://github.com/vectordotdev/vector/issues/6435

data_dir = "/app/vector_data"

# debug sink to console
[sinks.console]
type = "console"
inputs = ["service_file"]
encoding = { codec = "json" }